version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cloud-postgres-db
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: clouddb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d clouddb"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: cloud-api
    environment:
      DATABASE_URL: postgresql://dbuser:dbpassword@postgres:5432/clouddb
      JWT_SECRET: your-secret-key-change-in-production
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./config:/app/config

volumes:
  postgres_data: